### ISSUE TITLE
Scraping: Need to find a conform way to label time in hourly predictions

### ISSUE THREAD

**Issue by inesw** [BCCN-Prog/weather_2016#23]
What does the index in the hourly data format mean (absolute vs. relative times)? How do we achieve comparability? How can we implement a standardized time stamp?

**Comment by clauslang** [comment]
Since the timestamp in the dictionary passed from the data extraction scripts to the database consist only of YYYYMMDD, the index will probably have to denote absolute times, i.e. hours of the day.

**Comment by clauslang** [comment]
Then another question needs to be answered: How do we handle hourly predictions for the next day? How are they represented in the dictionary that gets passed to the database side? For instance, is 2 a.m. the next day just hourly index 26 or should a new dictionary for the next day be created? I have seen both solutions in the scraping scripts. 
For some, it doesn't make a difference, because they just consider the predictions for the same day, i.e. from 00:00 to 23:00.

**Comment by clauslang** [comment]
We have decided on the following:

- For predictions for the next day, a new dictionary has to be created and passed to the database side separately, that is, one hourly dictionary contains only the predictions for the date that is specified in the 'date' timestamp. The hourly indices denote the actual time that the prediction is for, e.g. index 19 is the index for the prediction for 7pm.
- On the highest hierarchy level of the dictionary, i.e. as neighbour to 'city', 'site', 'date', 'daily', 'hourly', the dictionary has to have another entry **'prediction_time'**, that denotes the time when the html file was downloaded as an int in the format YYYYMMDDHHMM. This should be easy to implement, since this timestamp is included in the file names.
- This information then has to be stored in an additional column in the hourly database.

Reasons:
- A new dictionary is a much cleaner way to handle this, with less potential ambiguity and less further error-prone processing on the database side.
- The indices denoting the actual time of the day makes the scraping database consistent with the historical database, which is conceptually nicer and will save us a lot of work when comparing predictions to actual values.
- Keeping the exact prediction time stamp allows us to still answer queries like "How good was the prediction of parameter x two hours earlier compared to 20 hours earlier."
