### ISSUE TITLE
owm script crashes

### ISSUE THREAD

**Issue by erensezener** [BCCN-Prog/weather_2016#3]
The log is not very explanatory unfortunately:

```

RUNNING <module 'wetter_com' from '/home/pcp2016/weather_2016/scraping/wetter_com/__init__.py'>
RUNNING <module 'owm' from '/home/pcp2016/weather_2016/scraping/owm/__init__.py'>
downloading html for hamburg
Excepted error in <module 'owm' from '/home/pcp2016/weather_2016/scraping/owm/__init__.py'>.

<class 'RuntimeError'>
RUNNING <module 'wetter_de' from '/home/pcp2016/weather_2016/scraping/wetter_de/__init__.py'>
RUNNING <module 'accuweather' from '/home/pcp2016/weather_2016/scraping/accuweather/__init__.py'>
```

**Comment by erensezener** [comment]
Also shouldn't there be 5 modules? @inesw @clauslang

**Comment by daveh19** [comment]
Does this mean that scripts are still crashing? Or is this part of the testing?

**Comment by erensezener** [comment]
The scripts are still crashing. It is because of an update though.

**Comment by clauslang** [comment]
There are five scripts now, right?

**Comment by clauslang** [comment]
So all of them are crashing? What kind of update do you mean?

**Comment by erensezener** [comment]
When I pulled at 5.40ish, the 5th script one was not added yet I guess. I will try to update it tomorrow. 

I meant owm is crashing probably due to the change. I will also look into that.

**Comment by clauslang** [comment]
Ok great. Let me know in case I can help in any way.

--------------------------------------------
C. Eren Sezener <notifications@github.com> schrieb am Fr, 6.5.2016:

 Betreff: Re: [BCCN-Prog/weather_2016] owm script crashes (#3)
 An: "BCCN-Prog/weather_2016" <weather_2016@noreply.github.com>
 CC: "clauslang" <clauslang@yahoo.de>, "Mention" <mention@noreply.github.com>
 Datum: Freitag, 6. Mai, 2016 11:11 Uhr
 
 When I pulled at 5.40ish, the 5th
 script one was not added yet I guess. I will try to update
 it tomorrow. 
 
 I meant owm is crashing probably due to the change. I
 will also look into that.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly or view
 it on GitHub

**Comment by erensezener** [comment]
Fixed it. I needed to install something like a display simulator for firefox.
