### ISSUE TITLE
Please fill in the wiki!

### ISSUE THREAD

**Issue by inesw** [BCCN-Prog/weather_2016#58]
Please remember to fill in the wiki. Share your ideas, ideally as concrete as possible (what data shall be used exactly? How shall the result be presented?). If you are already working on something that is supposed to be used for answering questions, please mention that! https://github.com/BCCN-Prog/weather_2016/wiki/Query-goals Please do it until Monday!  @clauslang

**Comment by WHops** [comment]
Okay, so yesterday night after a few beers, I had a gread idea for our presentation:

We make it a short sequence of acted everyday-situations where we show how totally necessary our program is. 

Example Scene:

Old guy and grandson are sitting in the kitchen. Rain outside. 
Old guy is like "Oh dear grandson, it's raining today, so that means it will rain the next 3 days as well, I'm sure you won't be able to go to your festival blablabla

His grandson, desperate expression, facing the audience: "I can't hear his stories anymore, if only I had a way to disprove this idiot!"

Godlike BCCN-master enters the scene, promises to solve all the world's problems.
Shows the grandson how simple it is to disprove that guy with the BCCN weather app. 

Old guy is shocked about how far technology has come nowadays.

-> happyness

The End.

In total, we have like 3 or 4 scenes, everytime with a different situation, where the godlike BCCN-master shortly shows our program's main features in a situation where somebody needs them. 

In the end we get a totally embarassing, non-serious and entertaining presentation that skips all the boring "what did we do and how did we do it" stuff. (Keep in mind to that point we will already have heard 4 totally serious presentations.) 

What do you think? What do you THINK?

**Comment by ge00rg** [comment]
I don't know what is expectoed from us in terms of the presentation (an I'm quite agnostic about how we do it), but the question in your scenario is interesting - given that it rained for x days, how likely is it that it rains the following y days. We can even pit this prediction against the one from the weather sites (and probably lose, but by what margin?). 

If would be helpful for me if you posted all such scnarios somewhere, because I realized for example that although you could compute that with the code we already have, it would be extremely suboptimal (->take ages) and I'll have to write a function for that.

**Comment by inesw** [comment]
Great idea, Wolfi!!
